name: python-daft-analyser

services:
  daft-scraper:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: daft-scraper
    env_file: ../.env
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=DEBUG
    shm_size: "256m"
    restart: unless-stopped
